### ISSUE TITLE
errno: 20, code: 'EMFILE'

### ISSUE THREAD

**Issue by biggbest** [mllrsohn/node-webkit-builder#169] opened 2015-01-24 17:44 UTC
I get this error while making the package. I'm not using Grunt or anything else, just nwbuild -o builds/ game/ :-)

File concerned: /node_modules/socket.io/lib/client.js

**Comment by adam-lynch** [comment] 2015-01-29 11:44
This is a duplicate of #142 I think.

**Closed by adam-lynch** 2015-01-29 11:44 UTC
