### ISSUE TITLE
HELP !!!!! Files on desktop disappeared.

### ISSUE THREAD

**Issue by lowdance** [mllrsohn/node-webkit-builder#182] opened 2015-02-05 17:25 UTC
Hi,

I use this on my desktop. And I lost all the files on it...
Is there a way to get them back ?

I'm using OSx

**Comment by trevorah** [comment] 2015-02-05 17:30
What commands did you run?

**Comment by lowdance** [comment] 2015-02-05 17:54
node ./node_modules/.bin/nwbuild desktop :/

**Comment by trevorah** [comment] 2015-02-05 18:10
I cant reproduce this, but if nothing shows up when you do an `ls -la ~/Desktop`, then you've lost those items. Sorry.

**Comment by lowdance** [comment] 2015-02-05 18:11
But where are the zipped files ?

**Comment by trevorah** [comment] 2015-02-05 18:12
What zipped files?

**Comment by lowdance** [comment] 2015-02-05 18:17
Any change these files are still in temp ?

**Comment by ComFreek** [comment] 2015-02-05 18:30
Well, you have always the chance to scan the HDD for those files. The point is that simple deletion of files doesn't remove them from the HDD, it just deletes their entries in the file table. Keep in mind that every action which writes to the HDD diminishes the Chance of a successful successful file recovery, so it's best to connect the HDD to another PC.

**Comment by trevorah** [comment] 2015-02-09 11:28
@lowdance im going to close this for now. Please reopen if you can reproduce this with a temporary directory.

**Closed by trevorah** 2015-02-09 11:28 UTC
Labels: question

**Comment by 1j01** [comment] 2015-02-16 17:41
Could the files be extracted from the exe if the node web kit exe in the build directory is built with the files?

**Comment by adam-lynch** [comment] 2015-02-16 18:22
@1j01 as far as I remember, yes. I'm not 100% sure but I think if you rename it to `.zip` and extract, then you'll get the files.

**Comment by 1j01** [comment] 2015-02-16 19:52
As long as the files are actually in there (I don't know), it should be possible for @bokzor to get them back from there. But if there were EMFILE errors when trying to open the file(s), it seems less hopeful.

**Comment by bokzor** [comment] 2015-02-16 20:14
Indeed. The build didn’t work. So no files to recover.




Nevermind….
